SistemaTCC\Model\EtapaEntregaArquivo:
    type: entity
    table: etapa_entrega_arquivo
    indexes:
        fk_etapa_entrega_arquivo_etapa_entrega1_idx:
            columns:
                - etapa_entrega_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        tipo:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        caminho:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        etapaEntrega:
            targetEntity: SistemaTCC\Model\EtapaEntrega
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                etapa_entrega_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
