SistemaTCC\Model\Professor:
    type: entity
    table: professor
    indexes:
        fk_professor_pessoa1_idx:
            columns:
                - pessoa_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        assinatura:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        pessoa:
            targetEntity: SistemaTCC\Model\Pessoa
            cascade: ["all"]
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pessoa_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        areasDeInteresse:
            targetEntity: SistemaTCC\Model\AreaDeInteresse
            cascade: { }
            inversedBy: professores
            joinTable:
                name: professor_area_de_interesse
                joinColumns:
                    professor_id:
                      referencedColumnName: id
                inverseJoinColumns:
                    area_de_interesse_id:
                      referencedColumnName: id

    lifecycleCallbacks: {  }
