SistemaTCC\Model\AreaDeInteresse:
    type: entity
    table: area_de_interesse
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titulo:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
    manyToMany:
        professores:
            cascade: { }
            targetEntity: SistemaTCC\Model\Professor
            mappedBy: areasDeInteresse

    lifecycleCallbacks: {  }
