SistemaTCC\Model\Tcc:
    type: entity
    table: tcc
    indexes:
        fk_aluno_tcc_aluno1_idx:
            columns:
                - aluno_id
        fk_tcc_semestre1_idx:
            columns:
                - semestre_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titulo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        aluno:
            targetEntity: SistemaTCC\Model\Aluno
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                aluno_id:
                    referencedColumnName: id
            orphanRemoval: false
        semestre:
            targetEntity: SistemaTCC\Model\Semestre
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                semestre_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
