CREATE TABLE atestado (id INT AUTO_INCREMENT NOT NULL, tcc_id INT DEFAULT NULL, professor_id INT DEFAULT NULL, data DATE NOT NULL, INDEX IDX_F6DBCB344F70A726 (tcc_id), INDEX IDX_F6DBCB347D2D84D5 (professor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE atestado ADD CONSTRAINT FK_F6DBCB344F70A726 FOREIGN KEY (tcc_id) REFERENCES tcc (id);
ALTER TABLE atestado ADD CONSTRAINT FK_F6DBCB347D2D84D5 FOREIGN KEY (professor_id) REFERENCES professor (id);
