SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE usuario DROP FOREIGN KEY FK_2265B05D6A41B146;
ALTER TABLE usuario DROP usuario_acesso_id;
ALTER TABLE usuario ADD nivel VARCHAR(255) NOT NULL;
DROP TABLE usuario_acesso;
SET FOREIGN_KEY_CHECKS = 1;
